apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  annotations:
    github.com/project-slug: HieuTVSE63007/test
spec:
  type: service
  lifecycle: production
  owner: HieuTVSE63007
